name: Hourly HTTP Request

on:
  schedule:
    # Runs at the beginning of every hour
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  ping_url:
    runs-on: ubuntu-latest
    steps:
      - name: Call the URL endpoint
        run: curl -sS "https://voice-ai-api-harpreets-projects-f8b2f14c.vercel.app/api/checkBlocks"
